name: continuous training
on:
  schedule:
    -cron:  '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: why to run this?
        required: false
        default: runninng CT
jobs:
  continuous-training:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: train model
        env:
          SERVICE_ACCOUNT_KEY: ${{secrets.SERVICE_ACCOUNT_KEY}}
        run: |
        pip3 install virtualenv
        virtualenv venv
        source venv/bin/activate
        pip install -r src/requirements_test.txt
        export  GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
        dvc pull model/model.pkl.dvc -r model-tracker
        dvc unprotect model/model.pkl
        dvc repo -f 
        echo 'training completed'
        dvc add model/model.pkl.dvc  -r model-tracker --to-remote
        dvc push model/model.pkl.dvc -r model-tracker
      - name: commit .dvc files
       run: |
        git config  --local user.email "juancamiloinfor62@gmail.com"
        git config  --local user.name "github-actions[bot]"
        git add model/model.pkl.dvc
        git commit -m  "updating model serialization"
     - uses: ad-m/github-push-action@master
       with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        branch: ${{github.ref}}
     - uses: iterative/setup-cml@v1
     - name: push metrics
       env:
        REPO_TOKENS: ${{secrets.GITHUB_TOKEN}}
        run: |
        cat report.txt >> report.md
        cml-publish prediction_behaviour.png --md >> report.md
        cml-send-comment report.md


